spring:
  r2dbc:
    url: r2dbc:h2:mem:///app-db
    generate-unique-name: true
  flyway:
    url: jdbc:h2:mem:app-db
  datasource:
    url: jdbc:h2:mem:app-db
    driverClassName: org.h2.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect