spring:
  r2dbc:
    username: root
    password: root
  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration
    user: root
    password: root
springdoc:
  api-docs:
    path: "/swagger-doc/v3/api-docs"
    enabled: true
  swagger-ui:
    path: /swagger-doc/v3/swagger-ui.html
    enabled: true
